import { Inter } from "next/font/google";
import "./globals.css";
import { MerchantFormProvider } from "@/contexts/MerchantFormContext";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <Suspense fallback={<> Loading...</>}>
      <MerchantFormProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </MerchantFormProvider>
    // </Suspense>
  );
}
